spring:
  main:
    banner-mode: off
  profiles:
    default: local
    group:
      local: local

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info
      path-mapping:
        health : healthcheck

server:
  port: 8082