spring:
  application:
    name: api-server
  main:
    banner-mode: off
  profiles:
    default: dev
    group:
      local: local
      dev: dev
      prod: prod

# ===============================
# = actuator, prometheus+
# ===============================
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, metrics, prometheus
      path-mapping:
        health: healthcheck

# ===============================
# = server config
# ===============================
server:
  port: 8082
  shutdown: graceful
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8

# ===============================
# = logback
# ===============================
logging:
  config: classpath:logback-spring.xml
