spring:
  main:
    banner-mode: off
  datasource:
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:~/palette;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: