spring:
  config:
    activate:
      on-profile: local
    import: 'aws-parameterstore:'

  # ===============================
  # = jpa
  # ===============================
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 1000

  # ===============================
  # = database
  # ===============================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/palette
    username: dbuser
    password: dbuser1234

  #  sql:
  #    init:
  #      mode: always

  # ===============================
  # = logging
  # ===============================
logging:
  pattern:
    file: '%highlight(%-5level) %X{X-HIT-TRANSACTION-ID} %d{yyyy-MM-dd HH:mm:ss} [%-5p] [%F]%M\(%L\): %m%n'
    console: '%highlight(%-5level) %X{X-HIT-TRANSACTION-ID} %d{yyyy-MM-dd HH:mm:ss} [%-5p] [%F]%M\(%L\): %m%n'
  logback:
    rollingpolicy:
      file-name-pattern: '${LOG_FILE}.%d{yyyy-MM-dd}.%i.log'
      max-history: 30
  file:
    name: ./server/logs/api.log
  level:
    root: INFO
    org.springframework.web: INFO

aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: '-'
    name: app-palette
    fail-fast: true

# ===============================
# = p6spy
# ===============================
decorator:
  datasource:
    p6spy:
      enable-logging: false

# ===============================
# = sentry
# ===============================
sentry:
  logging:
    enabled: false # local 비활성화