spring:
  main:
    banner-mode: off
  profiles:
    default: local
    group:
      local: local
      dev: dev

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info
      path-mapping:
        health: healthcheck

# ===============================
# = server config
# ===============================
server:
  port: 8082
  shutdown: graceful
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8
